server:
  port: 1000

spring:
  application:
    name: greeting-service
  config:
    import: optional:configserver:http://config-server:50000
  cloud:
    config:
      fail-fast: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    instance-id: ${spring.application.name}:${random.int}
